include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Core rules
    prefer_const_constructors: true
    avoid_print: true
    always_use_package_imports: true
    use_key_in_widget_constructors: true

    # Naming conventions
    camel_case_types: true               # Classes, enums, typedefs, extensions => UpperCamelCase
    non_constant_identifier_names: true  # Variables, parameters => lowerCamelCase
    library_prefixes: true               # Import prefixes => lowerCamelCase
    file_names: true                     # File names => snake_case.dart

